# Generated by Django 6.0.4 on 2026-04-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursbeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fachgebiet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matrikel_nummer', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAusweis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausweis_nummer', models.CharField(max_length=20, unique=True)),
                ('gueltig_bis', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('kursbeschreibung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uni_app.kursbeschreibung')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.professor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.semester')),
                ('studenten', models.ManyToManyField(to='uni_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='ausweis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uni_app.studentausweis'),
        ),
    ]
